<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MesControlAgv.Contracts\MesControlAgv.Contracts.csproj" />
    <ProjectReference Include="..\MesControlAgv.Domain\MesControlAgv.Domain.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
