<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\MesControlAgv.Contracts\MesControlAgv.Contracts.csproj" />
    <ProjectReference Include="..\MesControlAgv.Application\MesControlAgv.Application.csproj" />
    <ProjectReference Include="..\MesControlAgv.Domain\MesControlAgv.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.24" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**" />
    <EmbeddedResource Remove="artifacts\**" />
    <None Remove="artifacts\**" />
    <Content Remove="artifacts\**" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>


